version: "3"
services:
  mysql:
    container_name: tring-mysql
    build:
      context: ./db
      dockerfile: dev.M1.Dockerfile
    env_file: ./.env
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.conf:/etc/mysql/conf.d/my.conf
    ports:
      - "7122:3306"
    networks:
      - tring

  phpmyadmin:
    container_name: tring-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 7123:80
    env_file: ./.env
    depends_on:
      - mysql
    networks:
      - tring

  api:
    container_name: tring-api
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    env_file: ./.env
    volumes:
      - ./api/:/app
    ports:
      - 7121:3000
    depends_on:
      - mysql
    networks:
      - tring

  client:
    container_name: tring-client
    build:
      context: ./client
      dockerfile: dev.M1.Dockerfile
    env_file: ./.env
    volumes:
      - ./client:/app
    ports:
      - "7120:8080"
    depends_on:
      - api
    networks:
      - tring
    tty: true

volumes:
  mysql:

networks:
  tring:
    driver: bridge
