CREATE DATABASE IF NOT EXISTS tring_db;

USE tring_db;

CREATE TABLE IF NOT EXISTS times (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  uid INT NOT NULL,
  time INT NOT NULL,
  finish_at TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name TEXT,
  image TEXT,
  card TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);